import { useEffect, useMemo, useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { ArrowUp, Check, ChevronDown, ChevronLeft, ChevronRight, Cookie, MessageCircle, Settings2, X } from 'lucide-react';
import { useSite } from '../store/SiteStore';

export function SkipLink(){return <a className="skip-link" href="#main-content">Saltar al contenido principal</a>}

export function RouteMeta(){
  const {data}=useSite();const location=useLocation();
  useEffect(()=>{
    const project=data.projects.find(x=>location.pathname===`/portfolio/${x.slug}`);
    const service=data.services.find(x=>location.pathname===`/servicios/${x.slug}`);
    const page=data.pages.find(x=>x.slug===location.pathname);
    const entity=project||service||page;const title=entity?.seo?.title||project?.title||service?.name||page?.title||(location.pathname==='/portfolio'?'Portfolio':location.pathname==='/servicios'?'Servicios':location.pathname==='/planes'?'Planes':location.pathname==='/contacto'?'Contacto':location.pathname==='/sobre-mi'?'Sobre Jonathan':'JEP Designer');
    const description=entity?.seo?.description||project?.summary||service?.summary||page?.intro||'Branding, diseño gráfico, publicidad y experiencias digitales con intención.';
    document.title=`${title} — JEP Designer`;
    let meta=document.querySelector('meta[name="description"]');if(meta)meta.content=description;
    let canonical=document.querySelector('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical)}const base=(data.settings.domain||window.location.origin).replace(/\/$/,'');canonical.href=`${base}${location.pathname}`;
    const setMeta=(selector,attribute,value,content)=>{let node=document.querySelector(selector);if(!node){node=document.createElement('meta');node.setAttribute(attribute,value);document.head.appendChild(node)}node.content=content};
    const ogImage=entity?.seo?.image||project?.cover||data.settings.defaultOgImage||'/assets/portada.jpg';const absoluteImage=new URL(ogImage,base).href;setMeta('meta[property="og:title"]','property','og:title',`${title} — JEP Designer`);setMeta('meta[property="og:description"]','property','og:description',description);setMeta('meta[property="og:url"]','property','og:url',canonical.href);setMeta('meta[property="og:type"]','property','og:type',project?'article':'website');setMeta('meta[property="og:image"]','property','og:image',absoluteImage);setMeta('meta[property="og:image:alt"]','property','og:image:alt',entity?.title||entity?.name||'JEP Designer');setMeta('meta[name="twitter:card"]','name','twitter:card','summary_large_image');setMeta('meta[name="twitter:image"]','name','twitter:image',absoluteImage);setMeta('meta[name="robots"]','name','robots',entity?.seo?.noIndex?'noindex, nofollow':'index, follow');
    const schema={ '@context':'https://schema.org','@type':service?'Service':project?'CreativeWork':'ProfessionalService',name:service?.name||project?.title||data.settings.siteName,description,url:canonical.href,...(!service&&!project&&{email:data.settings.email,telephone:data.settings.whatsapp})};let jsonLd=document.querySelector('#jep-route-schema');if(!jsonLd){jsonLd=document.createElement('script');jsonLd.id='jep-route-schema';jsonLd.type='application/ld+json';document.head.appendChild(jsonLd)}jsonLd.textContent=JSON.stringify(schema);
  },[location.pathname,data]);
  return null;
}

export function FloatingWhatsApp(){const {data}=useSite();return <a className="whatsapp-float" href={`https://wa.me/${data.settings.whatsappRaw}?text=${encodeURIComponent('Hola Jonathan, quiero información sobre tus servicios.')}`} target="_blank" rel="noreferrer" aria-label="Contactar por WhatsApp"><MessageCircle/><span>Hablemos</span></a>}

export function ScrollTop(){const [visible,setVisible]=useState(false);useEffect(()=>{const onScroll=()=>setVisible(window.scrollY>700);window.addEventListener('scroll',onScroll,{passive:true});return()=>window.removeEventListener('scroll',onScroll)},[]);return visible?<button className="scroll-top" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})} aria-label="Volver arriba"><ArrowUp/></button>:null}

export function Breadcrumbs({items=[]}){return <nav className="breadcrumbs" aria-label="Migas de pan"><Link to="/">Inicio</Link>{items.map((item,index)=><span key={item.label}><ChevronRight/> {item.to&&index<items.length-1?<Link to={item.to}>{item.label}</Link>:<b>{item.label}</b>}</span>)}</nav>}

export function FAQAccordion({items=[]}){const [open,setOpen]=useState(0);return <div className="faq-list">{items.map((item,index)=>{const id=item.id||`faq-${index}`;const expanded=open===index;return <article className={expanded?'open':''} key={id}><h3><button id={`${id}-trigger`} onClick={()=>setOpen(expanded?-1:index)} aria-expanded={expanded} aria-controls={`${id}-panel`}><span className="faq-number">{String(index+1).padStart(2,'0')}</span><span className="faq-question"><b>{item.question}</b>{item.category&&<small>{item.category}</small>}</span><ChevronDown/></button></h3>{expanded&&<div id={`${id}-panel`} className="faq-answer" role="region" aria-labelledby={`${id}-trigger`}><p>{item.answer}</p></div>}</article>})}</div>}

export function TestimonialsCarousel({items=[]}){const [index,setIndex]=useState(0);if(!items.length)return null;const item=items[index];return <div className="testimonials-carousel"><div className="testimonial-rating">★★★★★</div><blockquote>“{item.quote}”</blockquote><div className="testimonial-person"><span>{item.name?.[0]}</span><div><b>{item.name}</b><small>{item.role} · {item.company}</small></div></div><div className="carousel-controls"><button onClick={()=>setIndex((index-1+items.length)%items.length)}><ChevronLeft/></button><span>{index+1} / {items.length}</span><button onClick={()=>setIndex((index+1)%items.length)}><ChevronRight/></button></div></div>}

export function PlanComparison({plans=[]}){
  const ordered=useMemo(()=>[...plans].sort((a,b)=>(a.order||0)-(b.order||0)),[plans]);
  const groups=useMemo(()=>ordered.map((plan,index)=>({plan,index,features:(plan.features||[]).filter(feature=>!/^todo el (paquete|plan)/i.test(feature))})),[ordered]);
  return <div className="plan-comparison" aria-label="Comparación de planes"><div className="comparison-head"><div><span>Comparación completa</span><small>Los planes superiores incluyen todo lo anterior.</small></div>{ordered.map((plan,index)=><div className={plan.featured?'featured':''} key={plan.id}><span>{plan.eyebrow}</span><b>{plan.name}</b><strong>${plan.price}</strong>{index>0&&<small>Incluye {ordered[index-1].name}</small>}</div>)}</div>{groups.map(({plan,index,features})=><section className="comparison-group" key={plan.id}><header><span>{String(index+1).padStart(2,'0')}</span><div><b>{index===0?'Base del plan':`Mejoras de ${plan.name}`}</b><small>{index===0?`Incluidas desde ${plan.name}`:`Se suman a todo ${ordered[index-1].name}`}</small></div></header>{features.map(feature=><div className="comparison-row" key={`${plan.id}-${feature}`}><span>{feature}</span>{ordered.map((column,columnIndex)=><i className={columnIndex>=index?'included':'not-included'} key={column.id}>{columnIndex>=index?<><Check/><small>Incluido</small></>:<span>—</span>}</i>)}</div>)}</section>)}</div>;
}

const CONSENT_KEY='jep-cookie-consent-v1';
export function CookieConsent(){const [consent,setConsent]=useState(()=>localStorage.getItem(CONSENT_KEY));const [settings,setSettings]=useState(false);const [prefs,setPrefs]=useState({necessary:true,preferences:true,analytics:false});if(consent)return null;const save=value=>{localStorage.setItem(CONSENT_KEY,JSON.stringify(value));setConsent('saved')};return <div className="cookie-banner"><button className="cookie-close" onClick={()=>save({necessary:true,preferences:false,analytics:false})}><X/></button><div className="cookie-icon"><Cookie/></div><div><b>Tu privacidad también importa.</b><p>Usamos almacenamiento necesario para recordar el tema y el cotizador. La analítica seguirá desactivada hasta que la aceptes.</p>{settings&&<div className="cookie-settings"><label><span><b>Necesarias</b><small>Funcionamiento y seguridad.</small></span><input type="checkbox" checked disabled/></label><label><span><b>Preferencias</b><small>Tema y opciones del sitio.</small></span><input type="checkbox" checked={prefs.preferences} onChange={e=>setPrefs({...prefs,preferences:e.target.checked})}/></label><label><span><b>Analítica</b><small>Medición anónima cuando se configure.</small></span><input type="checkbox" checked={prefs.analytics} onChange={e=>setPrefs({...prefs,analytics:e.target.checked})}/></label></div>}</div><div className="cookie-actions"><button className="button ghost small" onClick={()=>setSettings(!settings)}><Settings2/>Configurar</button><button className="button ghost small" onClick={()=>save({necessary:true,preferences:false,analytics:false})}>Solo necesarias</button><button className="button primary small" onClick={()=>save({necessary:true,preferences:true,analytics:true})}>Aceptar todas</button>{settings&&<button className="button small" onClick={()=>save(prefs)}>Guardar preferencias</button>}</div></div>}
