import { useEffect, useMemo, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Clock3, Copy, FileClock, FileDown, Filter, History, RotateCcw, Search, Trash2, X } from 'lucide-react';
import { useSite } from '../store/SiteStore';
import { ConfirmDialog, StudioDialog } from '../components/Feedback';

export function useEditorialDraft(item,onAutosave){
  const [form,setForm]=useState(item);const [dirty,setDirty]=useState(false);const [savedAt,setSavedAt]=useState(item.autosavedAt||null);const baseline=useRef(JSON.stringify(item));
  const update=next=>{setForm(current=>typeof next==='function'?next(current):next);setDirty(true)};
  useEffect(()=>{if(!dirty||!onAutosave)return;const timer=setTimeout(()=>{onAutosave({...form});setSavedAt(new Date().toISOString())},1100);return()=>clearTimeout(timer)},[form,dirty,onAutosave]);
  useEffect(()=>{const before=e=>{if(!dirty)return;e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',before);return()=>window.removeEventListener('beforeunload',before)},[dirty]);
  const markSaved=()=>{baseline.current=JSON.stringify(form);setDirty(false);setSavedAt(new Date().toISOString())};
  const canClose=()=>!dirty||window.confirm('Hay cambios sin guardar manualmente. El borrador automático se conserva, pero esta versión no quedará en el historial. ¿Cerrar?');
  return{form,setForm:update,dirty,savedAt,markSaved,canClose};
}

export function EditorialFields({form,onChange,kind='contenido'}){
  const status=form.status||(form.published===false?'draft':'published');
  return <section className="editorial-panel"><header><div><span className="eyebrow">Publicación y SEO</span><h3>Control editorial</h3></div><span className={`status ${status}`}>{status==='published'?'Publicado':status==='scheduled'?'Programado':'Borrador'}</span></header><div className="form-grid"><label className="field"><span>Estado</span><select value={status} onChange={e=>onChange({...form,status:e.target.value,published:e.target.value==='published'})}><option value="draft">Borrador privado</option><option value="published">Publicado</option><option value="scheduled">Programado</option></select></label><label className="field"><span>Fecha de publicación</span><input type="datetime-local" value={form.publishAt?String(form.publishAt).slice(0,16):''} onChange={e=>onChange({...form,publishAt:e.target.value?new Date(e.target.value).toISOString():null,status:e.target.value?'scheduled':status})}/></label></div><div className="editorial-separator"/><label className="field"><span>Título SEO personalizado</span><input value={form.seo?.title||''} maxLength="60" onChange={e=>onChange({...form,seo:{...form.seo,title:e.target.value}})} placeholder={form.title||form.name}/><small>{(form.seo?.title||'').length}/60 caracteres</small></label><label className="field"><span>Descripción SEO</span><textarea rows="3" maxLength="160" value={form.seo?.description||''} onChange={e=>onChange({...form,seo:{...form.seo,description:e.target.value}})} placeholder="Resumen para buscadores y redes sociales"/><small>{(form.seo?.description||'').length}/160 caracteres</small></label><label className="field"><span>Imagen Open Graph</span><input value={form.seo?.image||''} onChange={e=>onChange({...form,seo:{...form.seo,image:e.target.value}})} placeholder="/assets/portada.jpg"/></label><div className="verification-grid"><label><input type="checkbox" checked={Boolean(form.contentVerified)} onChange={e=>onChange({...form,contentVerified:e.target.checked})}/><span><b>Contenido verificado</b><small>Textos, precio, tiempos y condiciones revisados.</small></span></label>{kind==='proyecto'&&<label><input type="checkbox" checked={Boolean(form.rightsVerified)} onChange={e=>onChange({...form,rightsVerified:e.target.checked})}/><span><b>Derechos verificados</b><small>Imágenes y testimonios cuentan con autorización.</small></span></label>}</div></section>;
}

export function VersionHistory({collection,itemId,open,onClose}){const{data,restoreVersion,notify}=useSite();const[confirm,setConfirm]=useState(null);const versions=(data.versions||[]).filter(v=>v.collection===collection&&v.itemId===itemId);return <><StudioDialog open={open} onClose={onClose} title="Historial de versiones" eyebrow="Seguridad editorial"><div className="version-list">{versions.length?versions.map(version=><article key={version.id}><FileClock/><div><b>{version.label}</b><span>{new Date(version.createdAt).toLocaleString('es-EC')}</span><small>{version.snapshot.title||version.snapshot.name||'Contenido'}</small></div><button className="button ghost small" onClick={()=>setConfirm(version)}><RotateCcw/>Restaurar</button></article>):<div className="editorial-empty"><History/><b>Todavía no hay versiones</b><p>Se creará una copia antes de cada guardado manual.</p></div>}</div></StudioDialog><ConfirmDialog open={Boolean(confirm)} title="Restaurar esta versión" message="El estado actual se guardará automáticamente antes de restaurar. Podrás volver atrás desde el historial." confirmLabel="Restaurar versión" danger={false} onClose={()=>setConfirm(null)} onConfirm={()=>{restoreVersion(confirm.id);notify('Versión restaurada')}}/></>}

export function TrashAdmin(){const{data,restoreTrash,permanentlyDelete,notify}=useSite();const[confirm,setConfirm]=useState(null);const trash=data.trash||[];return <main className="admin-page"><div className="admin-page-head"><div><span className="eyebrow">JEP Designer / Admin</span><h1>Papelera</h1><p>Los elementos eliminados pueden recuperarse hasta que los borres definitivamente.</p></div></div><section className="admin-card trash-list">{trash.length?trash.map(record=><article key={record.id}><Trash2/><div><small>{record.collection}</small><b>{record.item.title||record.item.name||record.item.question||'Contenido eliminado'}</b><span>Eliminado {new Date(record.deletedAt).toLocaleString('es-EC')}</span></div><button className="button ghost small" onClick={()=>{restoreTrash(record.id);notify('Contenido restaurado')}}><RotateCcw/>Restaurar</button><button className="button danger-button small" onClick={()=>setConfirm(record)}><X/>Eliminar definitivamente</button></article>):<div className="editorial-empty"><Trash2/><b>La papelera está vacía</b><p>Los proyectos, páginas y contenidos eliminados aparecerán aquí.</p></div>}</section><ConfirmDialog open={Boolean(confirm)} title="Eliminar definitivamente" message="Esta acción no puede deshacerse. Revisa que el contenido no sea necesario antes de continuar." onClose={()=>setConfirm(null)} onConfirm={()=>{permanentlyDelete(confirm.id);notify('Elemento eliminado definitivamente')}}/></main>}

const routes={pages:'/admin/paginas',projects:'/admin/portfolio',services:'/admin/servicios',plans:'/admin/planes',inquiries:'/admin/consultas',categories:'/admin/categorias',faqs:'/admin/contenido',testimonials:'/admin/contenido'};
export function AdminSearch(){const{data}=useSite();const nav=useNavigate();const[query,setQuery]=useState('');const[open,setOpen]=useState(false);const results=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return[];return Object.entries(routes).flatMap(([collection,path])=>(data[collection]||[]).map(item=>({collection,path,id:item.id,label:item.title||item.name||item.question||item.serviceName||item.contact?.name||'Sin título',copy:item.summary||item.description||item.answer||item.contact?.email||''}))).filter(item=>`${item.label} ${item.copy}`.toLowerCase().includes(q)).slice(0,12)},[data,query]);return <div className="admin-global-search"><Search/><input value={query} onFocus={()=>setOpen(true)} onChange={e=>{setQuery(e.target.value);setOpen(true)}} onKeyDown={e=>e.key==='Escape'&&setOpen(false)} placeholder="Buscar páginas, proyectos, servicios, consultas…" aria-label="Buscar en administración"/>{query&&<button aria-label="Limpiar búsqueda" onClick={()=>setQuery('')}><X/></button>}{open&&query&&<div className="admin-search-results">{results.length?results.map(item=><button key={`${item.collection}-${item.id}`} onClick={()=>{nav(`${item.path}?focus=${item.id}`);setOpen(false);setQuery('')}}><small>{item.collection}</small><b>{item.label}</b><span>{item.copy}</span></button>):<p>Sin resultados para “{query}”.</p>}</div>}</div>}

export function useAdminList(items,{pageSize=8,searchFields=[],initialFilter='all'}={}){const[query,setQuery]=useState('');const[filter,setFilter]=useState(initialFilter);const[page,setPage]=useState(1);useEffect(()=>setPage(1),[query,filter]);const filtered=useMemo(()=>items.filter(item=>{const matches=!query||searchFields.some(field=>String(typeof field==='function'?field(item):item[field]||'').toLowerCase().includes(query.toLowerCase()));const state=item.status||(item.published===false?'draft':'published');return matches&&(filter==='all'||state===filter)}),[items,query,filter,searchFields]);const pages=Math.max(1,Math.ceil(filtered.length/pageSize));const visible=filtered.slice((page-1)*pageSize,page*pageSize);return{query,setQuery,filter,setFilter,page,setPage,pages,visible,total:filtered.length}}

export function AdminListToolbar({list,placeholder='Buscar…',showStatus=true,actions}){return <div className="editorial-toolbar"><label><Search/><input value={list.query} onChange={e=>list.setQuery(e.target.value)} placeholder={placeholder}/></label>{showStatus&&<label><Filter/><select value={list.filter} onChange={e=>list.setFilter(e.target.value)}><option value="all">Todos los estados</option><option value="published">Publicados</option><option value="draft">Borradores</option><option value="scheduled">Programados</option></select></label>}<span>{list.total} resultados</span>{actions}</div>}
export function Pagination({list}){if(list.pages<=1)return null;return <nav className="admin-pagination" aria-label="Paginación">{Array.from({length:list.pages},(_,i)=>i+1).map(number=><button className={number===list.page?'active':''} onClick={()=>list.setPage(number)} key={number}>{number}</button>)}</nav>}

const csvCell=value=>`"${String(value??'').replaceAll('"','""')}"`;
export function exportInquiriesCsv(items){const rows=[['Fecha','Nombre','Correo','Teléfono','Servicio','Estado','Notas'],...items.map(q=>[q.createdAt,q.contact?.name,q.contact?.email,q.contact?.phone,q.serviceName,q.status,q.internalNotes])];const blob=new Blob(['\ufeff'+rows.map(row=>row.map(csvCell).join(',')).join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`consultas-jep-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)}
export function exportInquiriesPdf(items){const win=window.open('','_blank','noopener,noreferrer');if(!win)return;const rows=items.map(q=>`<tr><td>${new Date(q.createdAt).toLocaleDateString('es-EC')}</td><td>${q.contact?.name||''}<br><small>${q.contact?.email||''}</small></td><td>${q.serviceName||''}</td><td>${q.status||''}</td><td>${q.internalNotes||''}</td></tr>`).join('');win.document.write(`<!doctype html><html><head><title>Consultas JEP Designer</title><style>body{font:13px Arial;padding:30px;color:#171411}h1{font-size:28px}table{width:100%;border-collapse:collapse}th,td{padding:10px;border:1px solid #ddd;text-align:left;vertical-align:top}th{background:#ff5a1f;color:#111}small{color:#666}@media print{body{padding:0}}</style></head><body><h1>Consultas — JEP Designer</h1><p>Exportado ${new Date().toLocaleString('es-EC')}</p><table><thead><tr><th>Fecha</th><th>Contacto</th><th>Servicio</th><th>Estado</th><th>Notas</th></tr></thead><tbody>${rows}</tbody></table><script>window.onload=()=>window.print()<\/script></body></html>`);win.document.close()}

export function EditorialActions({onDuplicate,onHistory,onTrash}){return <div className="row-actions"><button title="Duplicar" onClick={onDuplicate}><Copy/></button><button title="Historial" onClick={onHistory}><History/></button><button title="Mover a papelera" className="danger" onClick={onTrash}><Trash2/></button></div>}
export function ExportActions({items}){return <div className="export-actions"><button className="button ghost small" onClick={()=>exportInquiriesCsv(items)}><FileDown/>CSV</button><button className="button ghost small" onClick={()=>exportInquiriesPdf(items)}><FileDown/>PDF</button></div>}
