-- Contenido inicial generado desde src/data/seed.js. No editar manualmente.

-- Regenerar con: npm run db:seed-migration

insert into public.portfolio_categories (id, parent_id, name, slug, description, status, sort_order)
select x.id, x.parent_id, x.name, x.slug, x.description, x.status, x.sort_order
from jsonb_populate_record(null::public.portfolio_categories, $jep${"id":"personal","parent_id":null,"name":"Marcas personales","slug":"marcas-personales","description":"Identidades auténticas para profesionales y creadores.","status":"published","sort_order":1}$jep$::jsonb) as x
on conflict (id) do update set parent_id = excluded.parent_id, name = excluded.name, slug = excluded.slug, description = excluded.description, status = excluded.status, sort_order = excluded.sort_order;

insert into public.portfolio_categories (id, parent_id, name, slug, description, status, sort_order)
select x.id, x.parent_id, x.name, x.slug, x.description, x.status, x.sort_order
from jsonb_populate_record(null::public.portfolio_categories, $jep${"id":"corporate","parent_id":null,"name":"Marcas corporativas","slug":"marcas-corporativas","description":"Sistemas visuales consistentes para empresas.","status":"published","sort_order":2}$jep$::jsonb) as x
on conflict (id) do update set parent_id = excluded.parent_id, name = excluded.name, slug = excluded.slug, description = excluded.description, status = excluded.status, sort_order = excluded.sort_order;

insert into public.portfolio_categories (id, parent_id, name, slug, description, status, sort_order)
select x.id, x.parent_id, x.name, x.slug, x.description, x.status, x.sort_order
from jsonb_populate_record(null::public.portfolio_categories, $jep${"id":"branding","parent_id":null,"name":"Branding","slug":"branding","description":"Estrategia, identidad y aplicaciones de marca.","status":"published","sort_order":3}$jep$::jsonb) as x
on conflict (id) do update set parent_id = excluded.parent_id, name = excluded.name, slug = excluded.slug, description = excluded.description, status = excluded.status, sort_order = excluded.sort_order;

insert into public.portfolio_categories (id, parent_id, name, slug, description, status, sort_order)
select x.id, x.parent_id, x.name, x.slug, x.description, x.status, x.sort_order
from jsonb_populate_record(null::public.portfolio_categories, $jep${"id":"digital","parent_id":null,"name":"Digital & Web","slug":"digital-web","description":"Interfaces, landing pages y experiencias digitales.","status":"published","sort_order":4}$jep$::jsonb) as x
on conflict (id) do update set parent_id = excluded.parent_id, name = excluded.name, slug = excluded.slug, description = excluded.description, status = excluded.status, sort_order = excluded.sort_order;

insert into public.portfolio_categories (id, parent_id, name, slug, description, status, sort_order)
select x.id, x.parent_id, x.name, x.slug, x.description, x.status, x.sort_order
from jsonb_populate_record(null::public.portfolio_categories, $jep${"id":"editorial","parent_id":null,"name":"Editorial & Publicidad","slug":"editorial-publicidad","description":"Piezas gráficas, campañas y contenidos.","status":"published","sort_order":5}$jep$::jsonb) as x
on conflict (id) do update set parent_id = excluded.parent_id, name = excluded.name, slug = excluded.slug, description = excluded.description, status = excluded.status, sort_order = excluded.sort_order;

insert into public.portfolio_categories (id, parent_id, name, slug, description, status, sort_order)
select x.id, x.parent_id, x.name, x.slug, x.description, x.status, x.sort_order
from jsonb_populate_record(null::public.portfolio_categories, $jep${"id":"illustration","parent_id":null,"name":"Ilustración","slug":"ilustracion","description":"Personajes, escenas y recursos visuales originales.","status":"published","sort_order":6}$jep$::jsonb) as x
on conflict (id) do update set parent_id = excluded.parent_id, name = excluded.name, slug = excluded.slug, description = excluded.description, status = excluded.status, sort_order = excluded.sort_order;

insert into public.pages (id, slug, title, eyebrow, headline, intro, body, blocks, seo, status, published, publish_at, content_verified, sort_order)
select x.id, x.slug, x.title, x.eyebrow, x.headline, x.intro, x.body, x.blocks, x.seo, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.pages, $jep${"id":"home","slug":"/","title":"Jonathan","eyebrow":"Diseñador gráfico & publicista","headline":"Diseño estratégico para marcas que quieren destacar.","intro":"Transformo ideas en marcas sólidas, memorables y listas para competir. Branding, comunicación visual y experiencias digitales con intención.","body":[],"blocks":[{"id":"home-statement","type":"text","visible":true,"anchor":"enfoque","data":{"html":"<p class=\"eyebrow\">Diseño que resuelve</p><h2>No creo piezas aisladas. Construyo una presencia que la gente reconoce, entiende y recuerda.</h2><p>Trabajo contigo para convertir una idea, un negocio o una marca en un sistema visual claro, útil y preparado para crecer.</p>","width":"normal","align":"center"}},{"id":"home-summary","type":"columns","visible":true,"anchor":"resumen","data":{"count":3,"gap":"medium","columns":["<p class=\"eyebrow\">01 · Estrategia</p><h3>Primero entendemos.</h3><p>Objetivo, audiencia, competencia y personalidad antes de abrir cualquier programa de diseño.</p>","<p class=\"eyebrow\">02 · Identidad</p><h3>Después construimos.</h3><p>Logotipo, color, tipografía y recursos conectados por una dirección visual coherente.</p>","<p class=\"eyebrow\">03 · Activación</p><h3>Finalmente lo hacemos útil.</h3><p>La marca se adapta a redes, publicidad, impresos, empaques y experiencias digitales.</p>"]}},{"id":"home-about","type":"mediaText","visible":true,"anchor":"jonathan","data":{"image":"/assets/personaje-04.jpg","alt":"Jonathan Peña, diseñador de JEP Designer","eyebrow":"Jonathan Peña · Director creativo","title":"Creatividad cercana, decisiones profesionales.","text":"Soy diseñador gráfico y publicista. Acompaño a emprendedores y empresas desde la idea inicial hasta un sistema visual que puedan usar con seguridad. El proceso es directo, colaborativo y sin lenguaje complicado.","imageSide":"right","ratio":"4/3","fit":"cover","buttonLabel":"Conocer mi trabajo","buttonUrl":"/portfolio"}},{"id":"home-palette","type":"palette","visible":true,"anchor":"identidad","data":{"name":"Una identidad enérgica, digital y memorable.","colors":["#ff5a1f","#0c0b0a","#f5f2eb","#335cff"],"showValues":true}},{"id":"home-final-banner","type":"banner","visible":true,"anchor":"empezar","data":{"src":"/assets/banner.jpg","alt":"Universo creativo de JEP Designer","title":"Tu marca puede verse tan profesional como la imaginas.","overlay":true,"height":"large","align":"left"}},{"id":"home-final-action","type":"button","visible":true,"data":{"label":"Cuéntame tu proyecto","url":"/servicios","style":"primary","align":"center","newTab":false,"icon":"arrow"}}],"seo":{},"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":1}$jep$::jsonb) as x
on conflict (id) do update set slug = excluded.slug, title = excluded.title, eyebrow = excluded.eyebrow, headline = excluded.headline, intro = excluded.intro, body = excluded.body, blocks = excluded.blocks, seo = excluded.seo, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.pages (id, slug, title, eyebrow, headline, intro, body, blocks, seo, status, published, publish_at, content_verified, sort_order)
select x.id, x.slug, x.title, x.eyebrow, x.headline, x.intro, x.body, x.blocks, x.seo, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.pages, $jep${"id":"contact","slug":"/contacto","title":"Contacto","eyebrow":"Empecemos una conversación","headline":"Tu próxima gran idea puede empezar aquí.","intro":"Cuéntame qué estás imaginando. Te responderé con preguntas claras, próximos pasos y una propuesta a tu medida.","body":[],"blocks":[],"seo":{},"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":2}$jep$::jsonb) as x
on conflict (id) do update set slug = excluded.slug, title = excluded.title, eyebrow = excluded.eyebrow, headline = excluded.headline, intro = excluded.intro, body = excluded.body, blocks = excluded.blocks, seo = excluded.seo, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.pages (id, slug, title, eyebrow, headline, intro, body, blocks, seo, status, published, publish_at, content_verified, sort_order)
select x.id, x.slug, x.title, x.eyebrow, x.headline, x.intro, x.body, x.blocks, x.seo, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.pages, $jep${"id":"terms","slug":"/terminos","title":"Términos y condiciones","eyebrow":null,"headline":"Trabajamos mejor cuando todo está claro.","intro":"Condiciones generales para cotizaciones, tiempos, revisiones, pagos, entregables y propiedad intelectual.","body":[],"blocks":[],"seo":{},"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":3}$jep$::jsonb) as x
on conflict (id) do update set slug = excluded.slug, title = excluded.title, eyebrow = excluded.eyebrow, headline = excluded.headline, intro = excluded.intro, body = excluded.body, blocks = excluded.blocks, seo = excluded.seo, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.pages (id, slug, title, eyebrow, headline, intro, body, blocks, seo, status, published, publish_at, content_verified, sort_order)
select x.id, x.slug, x.title, x.eyebrow, x.headline, x.intro, x.body, x.blocks, x.seo, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.pages, $jep${"id":"cookies","slug":"/cookies","title":"Política de cookies","eyebrow":null,"headline":"Privacidad sin letra pequeña.","intro":"Información sobre las tecnologías utilizadas para mejorar la experiencia y medir el rendimiento del sitio.","body":[],"blocks":[],"seo":{},"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":4}$jep$::jsonb) as x
on conflict (id) do update set slug = excluded.slug, title = excluded.title, eyebrow = excluded.eyebrow, headline = excluded.headline, intro = excluded.intro, body = excluded.body, blocks = excluded.blocks, seo = excluded.seo, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.pages (id, slug, title, eyebrow, headline, intro, body, blocks, seo, status, published, publish_at, content_verified, sort_order)
select x.id, x.slug, x.title, x.eyebrow, x.headline, x.intro, x.body, x.blocks, x.seo, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.pages, $jep${"id":"privacy","slug":"/privacidad","title":"Política de privacidad","eyebrow":"Tus datos, bajo control","headline":"Transparencia desde el primer contacto.","intro":"Explicamos qué información se solicita, para qué se utiliza, durante cuánto tiempo se conserva y cómo puedes ejercer tus derechos.","body":[],"blocks":[],"seo":{},"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":5}$jep$::jsonb) as x
on conflict (id) do update set slug = excluded.slug, title = excluded.title, eyebrow = excluded.eyebrow, headline = excluded.headline, intro = excluded.intro, body = excluded.body, blocks = excluded.blocks, seo = excluded.seo, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.services (id, name, slug, summary, ideal_for, base_price, price_label, delivery_time, requirements, deliverables, questions, seo, status, published, publish_at, content_verified, sort_order)
select x.id, x.name, x.slug, x.summary, x.ideal_for, x.base_price, x.price_label, x.delivery_time, x.requirements, x.deliverables, x.questions, x.seo, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.services, $jep${"id":"s1","name":"Branding e identidad visual","slug":"branding","summary":"Construimos una marca coherente, reconocible y lista para crecer.","ideal_for":"Negocios nuevos o marcas que necesitan redefinir su posicionamiento.","base_price":280,"price_label":"Desde $280","delivery_time":"20–30 días","requirements":["Información del negocio y objetivos","Disponibilidad para reunión de diagnóstico","Referencias y competidores principales"],"deliverables":["Diagnóstico y dirección estratégica","Concepto creativo y moodboard","Sistema de logotipo y versiones","Paleta cromática y tipografías","Recursos gráficos y aplicaciones esenciales","Guía de identidad visual"],"questions":[{"id":"business","label":"Nombre de la marca y actividad principal","type":"text","required":true},{"id":"stage","label":"¿En qué etapa está la marca?","type":"radio","required":true,"options":["Idea nueva","En lanzamiento","Marca activa que necesita mejorar","Rebranding completo"]},{"id":"story","label":"Historia, propósito y propuesta de valor","type":"textarea","required":true},{"id":"audience","label":"Describe a tu cliente ideal","type":"textarea","required":true},{"id":"competitors","label":"Competidores o referentes directos","type":"textarea","required":false},{"id":"personality","label":"Elige la personalidad que debe transmitir","type":"checkbox","required":true,"options":["Profesional","Cercana","Innovadora","Premium","Audaz","Tradicional","Divertida"]},{"id":"applications","label":"¿Dónde se usará principalmente la identidad?","type":"checkbox","required":true,"options":["Redes sociales","Papelería","Sitio web","Local físico","Empaques","Uniformes","Publicidad"]},{"id":"colors","label":"Colores preferidos o que debemos evitar","type":"color-multi","required":false},{"id":"style","label":"Dirección visual aproximada","type":"radio","required":true,"options":["Minimalista","Audaz y enérgico","Elegante y premium","Orgánico y cercano","Tecnológico","Divertido","Aún no lo sé"]},{"id":"budget","label":"Presupuesto aproximado","type":"select","required":true,"options":["Menos de $100","$100–$300","$300–$700","$700–$1.500","Más de $1.500","Necesito orientación"]},{"id":"deadline","label":"Fecha ideal de entrega","type":"date","required":false},{"id":"references","label":"Adjunta referencias, textos o archivos de marca","type":"file","required":false,"help":"PDF, imágenes o documentos. Máximo 10 MB por archivo."}],"seo":{},"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":1}$jep$::jsonb) as x
on conflict (id) do update set name = excluded.name, slug = excluded.slug, summary = excluded.summary, ideal_for = excluded.ideal_for, base_price = excluded.base_price, price_label = excluded.price_label, delivery_time = excluded.delivery_time, requirements = excluded.requirements, deliverables = excluded.deliverables, questions = excluded.questions, seo = excluded.seo, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.services (id, name, slug, summary, ideal_for, base_price, price_label, delivery_time, requirements, deliverables, questions, seo, status, published, publish_at, content_verified, sort_order)
select x.id, x.name, x.slug, x.summary, x.ideal_for, x.base_price, x.price_label, x.delivery_time, x.requirements, x.deliverables, x.questions, x.seo, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.services, $jep${"id":"s2","name":"Diseño de logotipo","slug":"logotipo","summary":"Un símbolo propio, versátil y pensado para durar.","ideal_for":"Emprendimientos que necesitan una firma visual profesional y funcional.","base_price":75,"price_label":"Desde $75","delivery_time":"7–12 días","requirements":["Nombre definitivo de la marca","Descripción del negocio","Comentarios consolidados en cada revisión"],"deliverables":["Dos propuestas iniciales","Versiones horizontal, vertical e isotipo","Variantes a color, blanco y negro","Archivos PNG, JPEG, PDF y vector editable","Guía rápida de color y uso"],"questions":[{"id":"brandName","label":"Nombre exacto que aparecerá en el logotipo","type":"text","required":true},{"id":"tagline","label":"¿Debe incluir un eslogan? Escríbelo exactamente","type":"text","required":false},{"id":"sector","label":"Sector, productos o servicios de la marca","type":"textarea","required":true},{"id":"audience","label":"Público principal","type":"textarea","required":true},{"id":"logoType","label":"Tipo de logo que imaginas","type":"radio","required":true,"options":["Solo texto / logotipo","Símbolo + texto","Iniciales / monograma","Mascota o personaje","Quiero recomendación"]},{"id":"concepts","label":"Ideas, símbolos o conceptos que deseas explorar","type":"textarea","required":false},{"id":"avoid","label":"Símbolos, estilos o colores que debemos evitar","type":"textarea","required":false},{"id":"uses","label":"Usos principales","type":"checkbox","required":true,"options":["Redes sociales","Impresión","Rótulos","Empaques","Uniformes","Web y aplicaciones"]},{"id":"colors","label":"Colores de preferencia","type":"color-multi","required":false},{"id":"style","label":"Estilo esperado","type":"radio","required":true,"options":["Minimalista","Audaz y enérgico","Elegante y premium","Orgánico y cercano","Tecnológico","Divertido","Aún no lo sé"]},{"id":"budget","label":"Presupuesto aproximado","type":"select","required":true,"options":["Menos de $100","$100–$300","$300–$700","$700–$1.500","Más de $1.500","Necesito orientación"]},{"id":"deadline","label":"Fecha ideal de entrega","type":"date","required":false},{"id":"references","label":"Adjunta referencias, textos o archivos de marca","type":"file","required":false,"help":"PDF, imágenes o documentos. Máximo 10 MB por archivo."}],"seo":{},"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":2}$jep$::jsonb) as x
on conflict (id) do update set name = excluded.name, slug = excluded.slug, summary = excluded.summary, ideal_for = excluded.ideal_for, base_price = excluded.base_price, price_label = excluded.price_label, delivery_time = excluded.delivery_time, requirements = excluded.requirements, deliverables = excluded.deliverables, questions = excluded.questions, seo = excluded.seo, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.services (id, name, slug, summary, ideal_for, base_price, price_label, delivery_time, requirements, deliverables, questions, seo, status, published, publish_at, content_verified, sort_order)
select x.id, x.name, x.slug, x.summary, x.ideal_for, x.base_price, x.price_label, x.delivery_time, x.requirements, x.deliverables, x.questions, x.seo, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.services, $jep${"id":"s3","name":"Landing page","slug":"landing-page","summary":"Una página clara, rápida y orientada a convertir visitas en contactos.","ideal_for":"Servicios, campañas o productos que necesitan captar contactos y ventas.","base_price":320,"price_label":"Desde $320","delivery_time":"15–25 días","requirements":["Dominio o decisión de dominio","Textos, logotipo e imágenes disponibles","Acceso a servicios que deban integrarse"],"deliverables":["Arquitectura y wireframe","Diseño responsive","Desarrollo de una página","Formulario y llamada a la acción","Integración básica de analítica","Optimización visual y publicación"],"questions":[{"id":"business","label":"Nombre del negocio y enlace actual, si existe","type":"text","required":true},{"id":"objective","label":"Objetivo principal de la página","type":"radio","required":true,"options":["Recibir contactos","Vender un producto","Reservar citas","Presentar un servicio","Descargar un recurso","Validar una idea"]},{"id":"audience","label":"¿A quién debe convencer la página?","type":"textarea","required":true},{"id":"cta","label":"Acción principal que realizará el visitante","type":"text","required":true},{"id":"sections","label":"Secciones necesarias","type":"checkbox","required":true,"options":["Inicio / hero","Beneficios","Servicios","Proceso","Portfolio","Testimonios","Preguntas frecuentes","Precios","Contacto"]},{"id":"contentReady","label":"¿Tienes textos e imágenes listos?","type":"radio","required":true,"options":["Sí, todo listo","Tengo una parte","Necesito apoyo con textos","Necesito banco de imágenes"]},{"id":"integrations","label":"Integraciones necesarias","type":"checkbox","required":false,"options":["WhatsApp","Correo","Calendario de citas","Pasarela de pago","Google Maps","Redes sociales","Analítica"]},{"id":"domain","label":"¿Ya tienes dominio y hosting?","type":"radio","required":true,"options":["Sí, ambos","Solo dominio","No tengo ninguno","Necesito asesoría"]},{"id":"referencesWeb","label":"Comparte páginas que te gustan y explica por qué","type":"textarea","required":false},{"id":"budget","label":"Presupuesto aproximado","type":"select","required":true,"options":["Menos de $100","$100–$300","$300–$700","$700–$1.500","Más de $1.500","Necesito orientación"]},{"id":"deadline","label":"Fecha ideal de entrega","type":"date","required":false},{"id":"references","label":"Adjunta referencias, textos o archivos de marca","type":"file","required":false,"help":"PDF, imágenes o documentos. Máximo 10 MB por archivo."}],"seo":{},"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":3}$jep$::jsonb) as x
on conflict (id) do update set name = excluded.name, slug = excluded.slug, summary = excluded.summary, ideal_for = excluded.ideal_for, base_price = excluded.base_price, price_label = excluded.price_label, delivery_time = excluded.delivery_time, requirements = excluded.requirements, deliverables = excluded.deliverables, questions = excluded.questions, seo = excluded.seo, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.services (id, name, slug, summary, ideal_for, base_price, price_label, delivery_time, requirements, deliverables, questions, seo, status, published, publish_at, content_verified, sort_order)
select x.id, x.name, x.slug, x.summary, x.ideal_for, x.base_price, x.price_label, x.delivery_time, x.requirements, x.deliverables, x.questions, x.seo, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.services, $jep${"id":"s4","name":"Papelería corporativa","slug":"papeleria","summary":"Piezas impresas y digitales que mantienen tu marca consistente.","ideal_for":"Empresas con identidad definida que necesitan materiales profesionales.","base_price":90,"price_label":"Desde $90","delivery_time":"7–10 días","requirements":["Logotipo vectorial y manual de marca","Datos definitivos de contacto","Especificaciones de la imprenta, si existen"],"deliverables":["Diseños adaptados a cada pieza","Arte final para imprenta","Versiones digitales editables cuando aplique","Mockups de presentación","Archivos PDF listos para producción"],"questions":[{"id":"pieces","label":"¿Qué piezas necesitas?","type":"checkbox","required":true,"options":["Tarjeta de presentación","Hoja membretada","Sobre","Carpeta","Firma de correo","Factura / cotización","Carnet","Plantilla de presentación"]},{"id":"quantity","label":"Cantidad de personas o versiones con datos distintos","type":"number","required":true},{"id":"content","label":"Datos y textos que debe llevar cada pieza","type":"textarea","required":true},{"id":"print","label":"¿Se imprimirá o será solo digital?","type":"radio","required":true,"options":["Impresión","Digital","Ambos"]},{"id":"printer","label":"¿Tienes medidas o requisitos de la imprenta?","type":"textarea","required":false},{"id":"editable","label":"¿Necesitas archivos editables para cambiar datos?","type":"radio","required":true,"options":["Sí","No","Solo algunas piezas"]},{"id":"deadline","label":"Fecha ideal de entrega","type":"date","required":false},{"id":"budget","label":"Presupuesto aproximado","type":"select","required":true,"options":["Menos de $100","$100–$300","$300–$700","$700–$1.500","Más de $1.500","Necesito orientación"]},{"id":"references","label":"Adjunta referencias, textos o archivos de marca","type":"file","required":false,"help":"PDF, imágenes o documentos. Máximo 10 MB por archivo."}],"seo":{},"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":4}$jep$::jsonb) as x
on conflict (id) do update set name = excluded.name, slug = excluded.slug, summary = excluded.summary, ideal_for = excluded.ideal_for, base_price = excluded.base_price, price_label = excluded.price_label, delivery_time = excluded.delivery_time, requirements = excluded.requirements, deliverables = excluded.deliverables, questions = excluded.questions, seo = excluded.seo, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.services (id, name, slug, summary, ideal_for, base_price, price_label, delivery_time, requirements, deliverables, questions, seo, status, published, publish_at, content_verified, sort_order)
select x.id, x.name, x.slug, x.summary, x.ideal_for, x.base_price, x.price_label, x.delivery_time, x.requirements, x.deliverables, x.questions, x.seo, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.services, $jep${"id":"s5","name":"Vectorización","slug":"vectorizacion","summary":"Recuperamos logos e ilustraciones con calidad profesional.","ideal_for":"Marcas que solo conservan imágenes pequeñas, borrosas o sin archivo editable.","base_price":25,"price_label":"Desde $25","delivery_time":"1–3 días","requirements":["La imagen de mayor calidad disponible","Aclarar si se requiere copia exacta o corrección","Indicar el uso final"],"deliverables":["Redibujo vectorial limpio","Corrección básica de curvas y proporciones","Versiones a color y monocromáticas","Archivos AI, SVG, EPS, PDF y PNG"],"questions":[{"id":"asset","label":"¿Qué necesitas vectorizar?","type":"radio","required":true,"options":["Logotipo","Firma","Ilustración","Plano o gráfico","Ícono","Otro"]},{"id":"fidelity","label":"Resultado esperado","type":"radio","required":true,"options":["Copia exacta","Corregir detalles y proporciones","Rediseñar manteniendo la idea"]},{"id":"quality","label":"Describe la calidad y el estado del archivo actual","type":"textarea","required":false},{"id":"usage","label":"Uso final del vector","type":"checkbox","required":true,"options":["Impresión pequeña","Gran formato","Bordado","Corte de vinilo","Grabado / láser","Pantalla / web"]},{"id":"formats","label":"Formatos de entrega necesarios","type":"checkbox","required":true,"options":["AI","SVG","EPS","PDF","PNG transparente","DXF"]},{"id":"colors","label":"¿Se deben respetar colores exactos?","type":"radio","required":true,"options":["Sí, tengo códigos","Sí, tomar de la imagen","No, pueden corregirse"]},{"id":"deadline","label":"Fecha ideal de entrega","type":"date","required":false},{"id":"references","label":"Adjunta referencias, textos o archivos de marca","type":"file","required":false,"help":"PDF, imágenes o documentos. Máximo 10 MB por archivo."}],"seo":{},"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":5}$jep$::jsonb) as x
on conflict (id) do update set name = excluded.name, slug = excluded.slug, summary = excluded.summary, ideal_for = excluded.ideal_for, base_price = excluded.base_price, price_label = excluded.price_label, delivery_time = excluded.delivery_time, requirements = excluded.requirements, deliverables = excluded.deliverables, questions = excluded.questions, seo = excluded.seo, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.services (id, name, slug, summary, ideal_for, base_price, price_label, delivery_time, requirements, deliverables, questions, seo, status, published, publish_at, content_verified, sort_order)
select x.id, x.name, x.slug, x.summary, x.ideal_for, x.base_price, x.price_label, x.delivery_time, x.requirements, x.deliverables, x.questions, x.seo, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.services, $jep${"id":"s6","name":"Ilustración","slug":"ilustracion","summary":"Ilustraciones originales para campañas, productos y contenidos.","ideal_for":"Marcas y personas que buscan una pieza visual original y con derechos de uso definidos.","base_price":65,"price_label":"Desde $65","delivery_time":"5–15 días","requirements":["Descripción clara de la escena","Referencias de estilo","Uso y licencia requeridos"],"deliverables":["Boceto inicial","Ilustración final en alta resolución","Versión para el formato acordado","Archivos PNG, JPEG y PDF","Vector editable cuando el estilo lo permita"],"questions":[{"id":"subject","label":"¿Qué debemos ilustrar? Describe escena, personajes y acción","type":"textarea","required":true},{"id":"style","label":"Estilo de ilustración","type":"radio","required":true,"options":["Vectorial","Digital pintada","Cartoon / personaje","Editorial","Infantil","Realista","Necesito recomendación"]},{"id":"complexity","label":"Cantidad de personajes o elementos principales","type":"number","required":true},{"id":"format","label":"Medidas, orientación y resolución final","type":"text","required":true},{"id":"usage","label":"Uso de la ilustración","type":"checkbox","required":true,"options":["Redes sociales","Publicidad","Editorial","Producto / empaque","Merchandising","Uso personal","Animación posterior"]},{"id":"background","label":"Tipo de fondo","type":"radio","required":true,"options":["Transparente","Fondo simple","Escena completa","Varias versiones"]},{"id":"colors","label":"Paleta deseada","type":"color-multi","required":false},{"id":"license","label":"Alcance de uso","type":"radio","required":true,"options":["Personal","Comercial local","Campaña comercial","Uso indefinido / múltiples medios"]},{"id":"deadline","label":"Fecha ideal de entrega","type":"date","required":false},{"id":"budget","label":"Presupuesto aproximado","type":"select","required":true,"options":["Menos de $100","$100–$300","$300–$700","$700–$1.500","Más de $1.500","Necesito orientación"]},{"id":"references","label":"Adjunta referencias, textos o archivos de marca","type":"file","required":false,"help":"PDF, imágenes o documentos. Máximo 10 MB por archivo."}],"seo":{},"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":6}$jep$::jsonb) as x
on conflict (id) do update set name = excluded.name, slug = excluded.slug, summary = excluded.summary, ideal_for = excluded.ideal_for, base_price = excluded.base_price, price_label = excluded.price_label, delivery_time = excluded.delivery_time, requirements = excluded.requirements, deliverables = excluded.deliverables, questions = excluded.questions, seo = excluded.seo, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.services (id, name, slug, summary, ideal_for, base_price, price_label, delivery_time, requirements, deliverables, questions, seo, status, published, publish_at, content_verified, sort_order)
select x.id, x.name, x.slug, x.summary, x.ideal_for, x.base_price, x.price_label, x.delivery_time, x.requirements, x.deliverables, x.questions, x.seo, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.services, $jep${"id":"s7","name":"Contenido para redes sociales","slug":"redes-sociales","summary":"Sistemas visuales y piezas que hacen reconocible tu comunicación.","ideal_for":"Negocios que necesitan publicar con constancia y coherencia visual.","base_price":120,"price_label":"Desde $120","delivery_time":"7–15 días","requirements":["Identidad o logotipo disponible","Textos/promociones del periodo","Aprobaciones dentro del calendario"],"deliverables":["Dirección visual mensual","Plantillas o piezas finales","Adaptaciones por plataforma","Portadas y formatos acordados","Calendario visual de entregas"],"questions":[{"id":"platforms","label":"Redes que utilizarás","type":"checkbox","required":true,"options":["Instagram","Facebook","TikTok","LinkedIn","YouTube","Pinterest"]},{"id":"objective","label":"Objetivo principal","type":"radio","required":true,"options":["Reconocimiento de marca","Vender","Educar","Crear comunidad","Lanzar producto","Promocionar eventos"]},{"id":"monthly","label":"Cantidad estimada de piezas al mes","type":"select","required":true,"options":["4–6 piezas","8–10 piezas","12–15 piezas","16–20 piezas","Más de 20"]},{"id":"formats","label":"Formatos necesarios","type":"checkbox","required":true,"options":["Posts cuadrados","Carruseles","Stories","Portadas de reels","Banners","Miniaturas de video"]},{"id":"copy","label":"¿Quién entrega los textos?","type":"radio","required":true,"options":["Yo entrego textos finales","Necesito corrección","Necesito redacción completa"]},{"id":"photos","label":"¿Tienes fotografías o videos propios?","type":"radio","required":true,"options":["Sí","Parcialmente","No, usar banco de imágenes"]},{"id":"campaigns","label":"Fechas, promociones o campañas del periodo","type":"textarea","required":false},{"id":"tone","label":"Tono de comunicación","type":"checkbox","required":true,"options":["Profesional","Cercano","Educativo","Inspirador","Directo","Divertido"]},{"id":"budget","label":"Presupuesto aproximado","type":"select","required":true,"options":["Menos de $100","$100–$300","$300–$700","$700–$1.500","Más de $1.500","Necesito orientación"]},{"id":"deadline","label":"Fecha ideal de entrega","type":"date","required":false},{"id":"references","label":"Adjunta referencias, textos o archivos de marca","type":"file","required":false,"help":"PDF, imágenes o documentos. Máximo 10 MB por archivo."}],"seo":{},"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":7}$jep$::jsonb) as x
on conflict (id) do update set name = excluded.name, slug = excluded.slug, summary = excluded.summary, ideal_for = excluded.ideal_for, base_price = excluded.base_price, price_label = excluded.price_label, delivery_time = excluded.delivery_time, requirements = excluded.requirements, deliverables = excluded.deliverables, questions = excluded.questions, seo = excluded.seo, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.services (id, name, slug, summary, ideal_for, base_price, price_label, delivery_time, requirements, deliverables, questions, seo, status, published, publish_at, content_verified, sort_order)
select x.id, x.name, x.slug, x.summary, x.ideal_for, x.base_price, x.price_label, x.delivery_time, x.requirements, x.deliverables, x.questions, x.seo, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.services, $jep${"id":"s8","name":"Empaques y etiquetas","slug":"empaques","summary":"Diseño funcional para destacar en el punto de venta.","ideal_for":"Productos que necesitan verse profesionales y cumplir requisitos de producción.","base_price":160,"price_label":"Desde $160","delivery_time":"12–20 días","requirements":["Medidas o troquel de imprenta","Textos legales y datos del producto","Código de barras y sellos requeridos"],"deliverables":["Concepto visual del empaque","Diseño sobre troquel o medidas finales","Frente, reverso y laterales necesarios","Arte final con sangrados","Mockup de presentación"],"questions":[{"id":"product","label":"Producto, presentación y público","type":"textarea","required":true},{"id":"packageType","label":"Tipo de pieza","type":"checkbox","required":true,"options":["Caja","Bolsa","Etiqueta adhesiva","Faja / sleeve","Botella / envase","Doypack","Otro"]},{"id":"variants","label":"Cantidad de sabores, tamaños o variantes","type":"number","required":true},{"id":"dimensions","label":"Medidas exactas o enlace al troquel","type":"text","required":true},{"id":"material","label":"Material y sistema de impresión, si se conocen","type":"text","required":false},{"id":"legal","label":"¿Están listos ingredientes, registros y textos legales?","type":"radio","required":true,"options":["Sí, todo listo","Falta una parte","Necesito orientación de distribución"]},{"id":"barcode","label":"¿Tienes código de barras y sellos en alta calidad?","type":"radio","required":true,"options":["Sí","No","No aplica"]},{"id":"shelf","label":"¿Dónde competirá el producto y junto a qué marcas?","type":"textarea","required":false},{"id":"colors","label":"Colores de línea o variante","type":"color-multi","required":false},{"id":"budget","label":"Presupuesto aproximado","type":"select","required":true,"options":["Menos de $100","$100–$300","$300–$700","$700–$1.500","Más de $1.500","Necesito orientación"]},{"id":"deadline","label":"Fecha ideal de entrega","type":"date","required":false},{"id":"references","label":"Adjunta referencias, textos o archivos de marca","type":"file","required":false,"help":"PDF, imágenes o documentos. Máximo 10 MB por archivo."}],"seo":{},"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":8}$jep$::jsonb) as x
on conflict (id) do update set name = excluded.name, slug = excluded.slug, summary = excluded.summary, ideal_for = excluded.ideal_for, base_price = excluded.base_price, price_label = excluded.price_label, delivery_time = excluded.delivery_time, requirements = excluded.requirements, deliverables = excluded.deliverables, questions = excluded.questions, seo = excluded.seo, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.services (id, name, slug, summary, ideal_for, base_price, price_label, delivery_time, requirements, deliverables, questions, seo, status, published, publish_at, content_verified, sort_order)
select x.id, x.name, x.slug, x.summary, x.ideal_for, x.base_price, x.price_label, x.delivery_time, x.requirements, x.deliverables, x.questions, x.seo, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.services, $jep${"id":"s9","name":"Flyers y folletos","slug":"flyers","summary":"Información bien jerarquizada y visualmente atractiva.","ideal_for":"Promociones, eventos y servicios que necesitan comunicar rápido y con claridad.","base_price":35,"price_label":"Desde $35","delivery_time":"2–5 días","requirements":["Texto final revisado","Logotipo e imágenes disponibles","Medida y uso definidos"],"deliverables":["Diseño de la pieza acordada","Versión lista para imprenta","Versión optimizada para compartir","Archivo PDF y JPG/PNG"],"questions":[{"id":"piece","label":"Tipo de pieza","type":"radio","required":true,"options":["Flyer de una cara","Flyer de dos caras","Díptico","Tríptico","Folleto multipágina"]},{"id":"size","label":"Tamaño final","type":"select","required":true,"options":["A5","A4","Carta","Cuadrado","Medida personalizada"]},{"id":"purpose","label":"Promoción, evento o mensaje principal","type":"textarea","required":true},{"id":"content","label":"Pega el texto final y datos de contacto","type":"textarea","required":true},{"id":"distribution","label":"Forma de distribución","type":"checkbox","required":true,"options":["Impresión","WhatsApp","Correo","Redes sociales","Descarga web"]},{"id":"printer","label":"Especificaciones de imprenta o cantidad de copias","type":"textarea","required":false},{"id":"photos","label":"¿Cuentas con fotografías en alta calidad?","type":"radio","required":true,"options":["Sí","No","Usar banco de imágenes"]},{"id":"deadline","label":"Fecha ideal de entrega","type":"date","required":false},{"id":"references","label":"Adjunta referencias, textos o archivos de marca","type":"file","required":false,"help":"PDF, imágenes o documentos. Máximo 10 MB por archivo."}],"seo":{},"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":9}$jep$::jsonb) as x
on conflict (id) do update set name = excluded.name, slug = excluded.slug, summary = excluded.summary, ideal_for = excluded.ideal_for, base_price = excluded.base_price, price_label = excluded.price_label, delivery_time = excluded.delivery_time, requirements = excluded.requirements, deliverables = excluded.deliverables, questions = excluded.questions, seo = excluded.seo, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.services (id, name, slug, summary, ideal_for, base_price, price_label, delivery_time, requirements, deliverables, questions, seo, status, published, publish_at, content_verified, sort_order)
select x.id, x.name, x.slug, x.summary, x.ideal_for, x.base_price, x.price_label, x.delivery_time, x.requirements, x.deliverables, x.questions, x.seo, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.services, $jep${"id":"s10","name":"Pendones y avisos","slug":"avisos","summary":"Piezas de gran formato listas para impresión y producción.","ideal_for":"Locales, eventos y campañas que requieren visibilidad a distancia.","base_price":45,"price_label":"Desde $45","delivery_time":"3–6 días","requirements":["Medidas exactas","Distancia aproximada de lectura","Ficha técnica del proveedor cuando exista"],"deliverables":["Diseño adaptado a gran formato","Jerarquía para lectura a distancia","Arte final a escala con sangrado","PDF de producción y vista previa"],"questions":[{"id":"format","label":"Tipo de pieza","type":"checkbox","required":true,"options":["Roll up","Pendón","Lona","Valla","Aviso de fachada","Backing para evento","Vinilo"]},{"id":"dimensions","label":"Medidas exactas en centímetros o metros","type":"text","required":true},{"id":"location","label":"Lugar de instalación y distancia de lectura","type":"textarea","required":true},{"id":"message","label":"Mensaje principal y llamada a la acción","type":"textarea","required":true},{"id":"material","label":"Material o sistema de impresión","type":"text","required":false},{"id":"quantity","label":"Cantidad de diseños o variaciones","type":"number","required":true},{"id":"photos","label":"¿Hay imágenes en resolución suficiente?","type":"radio","required":true,"options":["Sí","No","Necesito selección de imágenes"]},{"id":"printer","label":"Adjunta plantilla o especificaciones del proveedor","type":"file","required":false},{"id":"deadline","label":"Fecha ideal de entrega","type":"date","required":false},{"id":"references","label":"Adjunta referencias, textos o archivos de marca","type":"file","required":false,"help":"PDF, imágenes o documentos. Máximo 10 MB por archivo."}],"seo":{},"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":10}$jep$::jsonb) as x
on conflict (id) do update set name = excluded.name, slug = excluded.slug, summary = excluded.summary, ideal_for = excluded.ideal_for, base_price = excluded.base_price, price_label = excluded.price_label, delivery_time = excluded.delivery_time, requirements = excluded.requirements, deliverables = excluded.deliverables, questions = excluded.questions, seo = excluded.seo, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.services (id, name, slug, summary, ideal_for, base_price, price_label, delivery_time, requirements, deliverables, questions, seo, status, published, publish_at, content_verified, sort_order)
select x.id, x.name, x.slug, x.summary, x.ideal_for, x.base_price, x.price_label, x.delivery_time, x.requirements, x.deliverables, x.questions, x.seo, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.services, $jep${"id":"s11","name":"Señalización","slug":"senalizacion","summary":"Sistemas claros para orientar, informar y reforzar la identidad.","ideal_for":"Espacios comerciales, oficinas e instituciones con recorridos y mensajes complejos.","base_price":140,"price_label":"Desde $140","delivery_time":"10–20 días","requirements":["Planos, fotos o recorrido del espacio","Listado preliminar de señales","Medidas y materiales disponibles"],"deliverables":["Inventario y jerarquía de señales","Sistema gráfico y pictogramas","Diseño de cada familia de señales","Especificaciones de medidas y color","Artes finales para producción"],"questions":[{"id":"space","label":"Tipo y tamaño aproximado del espacio","type":"textarea","required":true},{"id":"signalTypes","label":"Tipos de señal necesarios","type":"checkbox","required":true,"options":["Direccionales","Identificación de áreas","Normativas","Seguridad","Informativas","Accesibilidad","Fachada"]},{"id":"quantity","label":"Cantidad aproximada de señales","type":"number","required":true},{"id":"locations","label":"Sedes, pisos o zonas incluidas","type":"textarea","required":true},{"id":"measurements","label":"¿Tienes planos y medidas?","type":"radio","required":true,"options":["Sí, completos","Parcialmente","No, necesito levantamiento"]},{"id":"materials","label":"Materiales previstos","type":"checkbox","required":false,"options":["Acrílico","PVC","Metal","Madera","Vinilo","Impresión directa","Por definir"]},{"id":"installation","label":"¿Quién realizará producción e instalación?","type":"radio","required":true,"options":["Proveedor del cliente","Necesito recomendación","Aún no está definido"]},{"id":"accessibility","label":"Requisitos de accesibilidad o normativa","type":"textarea","required":false},{"id":"deadline","label":"Fecha ideal de entrega","type":"date","required":false},{"id":"budget","label":"Presupuesto aproximado","type":"select","required":true,"options":["Menos de $100","$100–$300","$300–$700","$700–$1.500","Más de $1.500","Necesito orientación"]},{"id":"references","label":"Adjunta referencias, textos o archivos de marca","type":"file","required":false,"help":"PDF, imágenes o documentos. Máximo 10 MB por archivo."}],"seo":{},"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":11}$jep$::jsonb) as x
on conflict (id) do update set name = excluded.name, slug = excluded.slug, summary = excluded.summary, ideal_for = excluded.ideal_for, base_price = excluded.base_price, price_label = excluded.price_label, delivery_time = excluded.delivery_time, requirements = excluded.requirements, deliverables = excluded.deliverables, questions = excluded.questions, seo = excluded.seo, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.services (id, name, slug, summary, ideal_for, base_price, price_label, delivery_time, requirements, deliverables, questions, seo, status, published, publish_at, content_verified, sort_order)
select x.id, x.name, x.slug, x.summary, x.ideal_for, x.base_price, x.price_label, x.delivery_time, x.requirements, x.deliverables, x.questions, x.seo, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.services, $jep${"id":"s12","name":"Catálogos digitales","slug":"catalogos","summary":"Presenta tus productos con orden, intención y una lectura fluida.","ideal_for":"Empresas con varios productos o servicios que necesitan una presentación organizada.","base_price":120,"price_label":"Desde $120","delivery_time":"10–20 días","requirements":["Listado estructurado de productos","Textos y precios definitivos","Fotografías organizadas por producto"],"deliverables":["Diseño de portada y sistema de páginas","Diagramación completa","Índice y navegación básica","PDF optimizado para pantalla","PDF listo para impresión si se solicita"],"questions":[{"id":"catalogType","label":"Tipo de catálogo","type":"radio","required":true,"options":["Productos","Servicios","Corporativo","Portafolio","Lista de precios"]},{"id":"items","label":"Cantidad aproximada de productos o servicios","type":"number","required":true},{"id":"pages","label":"Número estimado de páginas","type":"select","required":true,"options":["Hasta 8","9–16","17–32","33–60","Más de 60"]},{"id":"orientation","label":"Formato y orientación","type":"radio","required":true,"options":["A4 vertical","A4 horizontal","Cuadrado","Solo móvil","Medida personalizada"]},{"id":"dataReady","label":"Estado de textos, precios y fichas","type":"radio","required":true,"options":["Todo listo y organizado","Listo pero desorganizado","Falta contenido","Necesito ayuda para estructurarlo"]},{"id":"photos","label":"Estado de las fotografías","type":"radio","required":true,"options":["Alta calidad y organizadas","Calidad variable","Necesito banco de imágenes","Necesito sesión fotográfica"]},{"id":"interactive","label":"Funciones digitales","type":"checkbox","required":false,"options":["Índice clicable","Enlaces a WhatsApp","Enlaces a productos","Formulario externo","Código QR"]},{"id":"print","label":"¿También se imprimirá?","type":"radio","required":true,"options":["Sí","No","Tal vez después"]},{"id":"deadline","label":"Fecha ideal de entrega","type":"date","required":false},{"id":"budget","label":"Presupuesto aproximado","type":"select","required":true,"options":["Menos de $100","$100–$300","$300–$700","$700–$1.500","Más de $1.500","Necesito orientación"]},{"id":"references","label":"Adjunta referencias, textos o archivos de marca","type":"file","required":false,"help":"PDF, imágenes o documentos. Máximo 10 MB por archivo."}],"seo":{},"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":12}$jep$::jsonb) as x
on conflict (id) do update set name = excluded.name, slug = excluded.slug, summary = excluded.summary, ideal_for = excluded.ideal_for, base_price = excluded.base_price, price_label = excluded.price_label, delivery_time = excluded.delivery_time, requirements = excluded.requirements, deliverables = excluded.deliverables, questions = excluded.questions, seo = excluded.seo, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.services (id, name, slug, summary, ideal_for, base_price, price_label, delivery_time, requirements, deliverables, questions, seo, status, published, publish_at, content_verified, sort_order)
select x.id, x.name, x.slug, x.summary, x.ideal_for, x.base_price, x.price_label, x.delivery_time, x.requirements, x.deliverables, x.questions, x.seo, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.services, $jep${"id":"s13","name":"Menú digital","slug":"menu-digital","summary":"Una experiencia visual clara para restaurantes y negocios.","ideal_for":"Restaurantes, cafeterías y servicios con precios o productos organizados por categorías.","base_price":80,"price_label":"Desde $80","delivery_time":"5–10 días","requirements":["Listado final de platos y precios","Logotipo y estilo del local","Fotografías disponibles o decisión tipográfica"],"deliverables":["Diseño de portada y categorías","Diagramación de productos y precios","Versión PDF para QR y WhatsApp","Archivo para impresión si se requiere","Código QR básico"],"questions":[{"id":"businessType","label":"Tipo de establecimiento","type":"select","required":true,"options":["Restaurante","Cafetería","Bar","Pastelería","Comida rápida","Servicio a domicilio","Otro"]},{"id":"sections","label":"Categorías del menú","type":"textarea","required":true},{"id":"items","label":"Cantidad aproximada de productos","type":"number","required":true},{"id":"languages","label":"Idiomas necesarios","type":"checkbox","required":true,"options":["Español","Inglés","Portugués","Otro"]},{"id":"prices","label":"¿Los nombres, descripciones y precios están listos?","type":"radio","required":true,"options":["Sí","Falta revisar","Necesito ayuda para organizarlos"]},{"id":"photos","label":"Uso de fotografías","type":"radio","required":true,"options":["Una por producto","Solo productos destacados","Sin fotografías","Necesito banco de imágenes"]},{"id":"updates","label":"Frecuencia estimada de cambios","type":"radio","required":true,"options":["Rara vez","Mensual","Semanal","Temporadas y promociones"]},{"id":"formats","label":"Formatos requeridos","type":"checkbox","required":true,"options":["PDF para QR","WhatsApp","Pantalla / TV","Impresión de mesa","Menú mural"]},{"id":"allergens","label":"¿Deben incluirse ingredientes, alérgenos o íconos?","type":"textarea","required":false},{"id":"deadline","label":"Fecha ideal de entrega","type":"date","required":false},{"id":"budget","label":"Presupuesto aproximado","type":"select","required":true,"options":["Menos de $100","$100–$300","$300–$700","$700–$1.500","Más de $1.500","Necesito orientación"]},{"id":"references","label":"Adjunta referencias, textos o archivos de marca","type":"file","required":false,"help":"PDF, imágenes o documentos. Máximo 10 MB por archivo."}],"seo":{},"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":13}$jep$::jsonb) as x
on conflict (id) do update set name = excluded.name, slug = excluded.slug, summary = excluded.summary, ideal_for = excluded.ideal_for, base_price = excluded.base_price, price_label = excluded.price_label, delivery_time = excluded.delivery_time, requirements = excluded.requirements, deliverables = excluded.deliverables, questions = excluded.questions, seo = excluded.seo, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.services (id, name, slug, summary, ideal_for, base_price, price_label, delivery_time, requirements, deliverables, questions, seo, status, published, publish_at, content_verified, sort_order)
select x.id, x.name, x.slug, x.summary, x.ideal_for, x.base_price, x.price_label, x.delivery_time, x.requirements, x.deliverables, x.questions, x.seo, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.services, $jep${"id":"s14","name":"Marketing y publicidad","slug":"marketing","summary":"Conceptos de campaña y piezas conectadas con tus objetivos.","ideal_for":"Marcas que necesitan una campaña coherente en varios canales y formatos.","base_price":220,"price_label":"Desde $220","delivery_time":"15–30 días","requirements":["Objetivo comercial medible","Información del producto u oferta","Presupuesto y periodo de campaña definidos"],"deliverables":["Diagnóstico y concepto de campaña","Mensaje central y línea visual","Plan de piezas por canal","Diseños maestros y adaptaciones","Recomendaciones de publicación y medición"],"questions":[{"id":"campaign","label":"Producto, servicio u oferta a promocionar","type":"textarea","required":true},{"id":"objective","label":"Objetivo principal","type":"radio","required":true,"options":["Reconocimiento","Generar contactos","Ventas","Lanzamiento","Tráfico a local","Evento","Fidelización"]},{"id":"audience","label":"Público, ubicación y comportamiento","type":"textarea","required":true},{"id":"channels","label":"Canales previstos","type":"checkbox","required":true,"options":["Meta Ads","Instagram orgánico","TikTok","Google Ads","Correo","WhatsApp","Impresos","Vallas / exterior"]},{"id":"duration","label":"Duración de la campaña","type":"select","required":true,"options":["1–2 semanas","1 mes","2–3 meses","Campaña permanente"]},{"id":"mediaBudget","label":"Presupuesto exclusivo para pauta publicitaria","type":"select","required":true,"options":["Sin pauta","$50–$150","$150–$500","$500–$1.500","Más de $1.500"]},{"id":"deliverables","label":"Piezas que imaginas necesarias","type":"textarea","required":false},{"id":"kpis","label":"¿Cómo sabrás que la campaña funcionó?","type":"checkbox","required":true,"options":["Alcance","Mensajes","Registros","Ventas","Visitas al sitio","Visitas al local"]},{"id":"past","label":"Campañas anteriores y resultados","type":"textarea","required":false},{"id":"deadline","label":"Fecha ideal de entrega","type":"date","required":false},{"id":"budget","label":"Presupuesto aproximado","type":"select","required":true,"options":["Menos de $100","$100–$300","$300–$700","$700–$1.500","Más de $1.500","Necesito orientación"]},{"id":"references","label":"Adjunta referencias, textos o archivos de marca","type":"file","required":false,"help":"PDF, imágenes o documentos. Máximo 10 MB por archivo."}],"seo":{},"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":14}$jep$::jsonb) as x
on conflict (id) do update set name = excluded.name, slug = excluded.slug, summary = excluded.summary, ideal_for = excluded.ideal_for, base_price = excluded.base_price, price_label = excluded.price_label, delivery_time = excluded.delivery_time, requirements = excluded.requirements, deliverables = excluded.deliverables, questions = excluded.questions, seo = excluded.seo, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.plans (id, name, eyebrow, price, description, ideal_for, delivery_time, revisions, features, formats, not_included, featured, seo, status, published, publish_at, content_verified, sort_order)
select x.id, x.name, x.eyebrow, x.price, x.description, x.ideal_for, x.delivery_time, x.revisions, x.features, x.formats, x.not_included, x.featured, x.seo, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.plans, $jep${"id":"essential","name":"Esencial","eyebrow":"Para comenzar","price":75,"description":"Una base profesional para emprendimientos que están iniciando y necesitan un logotipo listo para trabajar.","ideal_for":"Emprendedores con nombre definido, una idea clara y necesidad inmediata de una identidad básica.","delivery_time":"7–10 días laborables","revisions":"1 ronda de ajustes","features":["Cuestionario inicial de marca","2 propuestas de logotipo","Logotipo principal aprobado","Versión horizontal o secundaria","Versión a color y monocromática","Paleta básica de 3–5 colores","Archivos para uso digital e impresión"],"formats":["PNG transparente","JPEG","PDF para impresión"],"not_included":["Manual de marca","Papelería corporativa","Plantillas para redes"],"featured":false,"seo":{},"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":1}$jep$::jsonb) as x
on conflict (id) do update set name = excluded.name, eyebrow = excluded.eyebrow, price = excluded.price, description = excluded.description, ideal_for = excluded.ideal_for, delivery_time = excluded.delivery_time, revisions = excluded.revisions, features = excluded.features, formats = excluded.formats, not_included = excluded.not_included, featured = excluded.featured, seo = excluded.seo, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.plans (id, name, eyebrow, price, description, ideal_for, delivery_time, revisions, features, formats, not_included, featured, seo, status, published, publish_at, content_verified, sort_order)
select x.id, x.name, x.eyebrow, x.price, x.description, x.ideal_for, x.delivery_time, x.revisions, x.features, x.formats, x.not_included, x.featured, x.seo, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.plans, $jep${"id":"professional","name":"Profesional","eyebrow":"La opción equilibrada","price":150,"description":"Una identidad visual coherente para marcas que quieren presentarse con seguridad en todos sus canales.","ideal_for":"Negocios activos que necesitan consistencia entre logotipo, colores, tipografías y redes sociales.","delivery_time":"12–18 días laborables","revisions":"2 rondas de ajustes","features":["Todo el paquete Esencial","3 propuestas o rutas visuales","Sistema de logotipo y versiones","Brand board completo","Paleta cromática con códigos HEX, RGB y CMYK","Selección tipográfica y jerarquías","Estilo fotográfico y recursos gráficos","3 plantillas editables para redes sociales","Mockups de presentación"],"formats":["AI editable","SVG","PNG","JPEG","PDF"],"not_included":["Manual de marca extendido","Estrategia verbal completa","Diseño de sitio web"],"featured":true,"seo":{},"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":2}$jep$::jsonb) as x
on conflict (id) do update set name = excluded.name, eyebrow = excluded.eyebrow, price = excluded.price, description = excluded.description, ideal_for = excluded.ideal_for, delivery_time = excluded.delivery_time, revisions = excluded.revisions, features = excluded.features, formats = excluded.formats, not_included = excluded.not_included, featured = excluded.featured, seo = excluded.seo, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.plans (id, name, eyebrow, price, description, ideal_for, delivery_time, revisions, features, formats, not_included, featured, seo, status, published, publish_at, content_verified, sort_order)
select x.id, x.name, x.eyebrow, x.price, x.description, x.ideal_for, x.delivery_time, x.revisions, x.features, x.formats, x.not_included, x.featured, x.seo, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.plans, $jep${"id":"premium","name":"Premium","eyebrow":"Sistema completo","price":300,"description":"Un sistema de identidad preparado para crecer, delegar diseño y mantener una imagen sólida y consistente.","ideal_for":"Empresas y marcas con varios canales, proveedores o colaboradores que necesitan reglas claras de uso.","delivery_time":"20–30 días laborables","revisions":"3 rondas de ajustes","features":["Todo el paquete Profesional","Diagnóstico y dirección estratégica","Manual de marca de 15–25 páginas","Construcción y área de seguridad del logo","Usos correctos e incorrectos","Sistema cromático completo","Tipografías oficiales y alternativas","Aplicaciones del logotipo","Papelería corporativa esencial","6 plantillas editables para redes","Kit organizado de archivos finales","Reunión de entrega y guía de uso"],"formats":["AI editable","SVG","EPS","PNG","JPEG","PDF"],"not_included":["Registro legal de marca","Impresión física","Gestión mensual de redes"],"featured":false,"seo":{},"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":3}$jep$::jsonb) as x
on conflict (id) do update set name = excluded.name, eyebrow = excluded.eyebrow, price = excluded.price, description = excluded.description, ideal_for = excluded.ideal_for, delivery_time = excluded.delivery_time, revisions = excluded.revisions, features = excluded.features, formats = excluded.formats, not_included = excluded.not_included, featured = excluded.featured, seo = excluded.seo, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.projects (id, category_id, title, slug, summary, body, blocks, cover_url, gallery, video_url, tags, services, client, project_year, featured, seo, rights_verified, status, published, publish_at, content_verified, sort_order)
select x.id, x.category_id, x.title, x.slug, x.summary, x.body, x.blocks, x.cover_url, x.gallery, x.video_url, x.tags, x.services, x.client, x.project_year, x.featured, x.seo, x.rights_verified, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.projects, $jep${"id":"p1","category_id":"personal","title":"JEP Designer — Identidad en movimiento","slug":"jep-identidad","summary":"Una identidad personal energética que convierte herramientas de diseño en un universo reconocible.","body":"El proyecto reúne estrategia, logotipo, sistema cromático, personaje 3D y aplicaciones para redes sociales. El reto fue equilibrar una estética tecnológica con una presencia cercana y memorable.","blocks":[{"id":"b-demo-1","type":"mediaText","visible":true,"data":{"image":"/assets/marca.jpg","alt":"Sistema visual JEP Designer","eyebrow":"Dirección creativa","title":"Una identidad que convierte herramientas en personalidad.","text":"El universo visual combina energía naranja, fondos oscuros, tipografía expresiva y un personaje cercano para comunicar creatividad sin perder profesionalismo.","imageSide":"left","ratio":"4/3","fit":"cover","buttonLabel":"","buttonUrl":""}},{"id":"b-demo-2","type":"palette","visible":true,"data":{"name":"Energía digital","colors":["#ff5a1f","#0c0b0a","#f5f2eb","#3b82f6"],"showValues":true}},{"id":"b-demo-3","type":"gallery","visible":true,"data":{"images":["/assets/marca.jpg","/assets/banner.jpg","/assets/diseno-fondo.jpg"],"layout":"mosaic","columns":3,"ratio":"4/3","fit":"cover"}}],"cover_url":"/assets/portada.jpg","gallery":["/assets/marca.jpg","/assets/banner.jpg","/assets/diseno-fondo.jpg"],"video_url":null,"tags":["branding","marca personal","logo","3D"],"services":["Estrategia","Identidad visual","Dirección de arte"],"client":"JEP Designer","project_year":"2026","featured":true,"seo":{},"rights_verified":false,"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":0}$jep$::jsonb) as x
on conflict (id) do update set category_id = excluded.category_id, title = excluded.title, slug = excluded.slug, summary = excluded.summary, body = excluded.body, blocks = excluded.blocks, cover_url = excluded.cover_url, gallery = excluded.gallery, video_url = excluded.video_url, tags = excluded.tags, services = excluded.services, client = excluded.client, project_year = excluded.project_year, featured = excluded.featured, seo = excluded.seo, rights_verified = excluded.rights_verified, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.projects (id, category_id, title, slug, summary, body, blocks, cover_url, gallery, video_url, tags, services, client, project_year, featured, seo, rights_verified, status, published, publish_at, content_verified, sort_order)
select x.id, x.category_id, x.title, x.slug, x.summary, x.body, x.blocks, x.cover_url, x.gallery, x.video_url, x.tags, x.services, x.client, x.project_year, x.featured, x.seo, x.rights_verified, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.projects, $jep${"id":"p2","category_id":"corporate","title":"Nexo — Una marca que conecta","slug":"nexo-corporativo","summary":"Sistema de identidad corporativa pensado para crecer sin perder coherencia.","body":"Desde la arquitectura de marca hasta la papelería, diseñamos un lenguaje visual flexible y profesional para múltiples puntos de contacto.","blocks":[],"cover_url":"/assets/marca.jpg","gallery":["/assets/diseno.jpg","/assets/ui-paquetes.jpg"],"video_url":null,"tags":["corporativo","manual de marca","papelería"],"services":["Branding","Papelería"],"client":"Nexo","project_year":"2025","featured":true,"seo":{},"rights_verified":false,"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":0}$jep$::jsonb) as x
on conflict (id) do update set category_id = excluded.category_id, title = excluded.title, slug = excluded.slug, summary = excluded.summary, body = excluded.body, blocks = excluded.blocks, cover_url = excluded.cover_url, gallery = excluded.gallery, video_url = excluded.video_url, tags = excluded.tags, services = excluded.services, client = excluded.client, project_year = excluded.project_year, featured = excluded.featured, seo = excluded.seo, rights_verified = excluded.rights_verified, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.projects (id, category_id, title, slug, summary, body, blocks, cover_url, gallery, video_url, tags, services, client, project_year, featured, seo, rights_verified, status, published, publish_at, content_verified, sort_order)
select x.id, x.category_id, x.title, x.slug, x.summary, x.body, x.blocks, x.cover_url, x.gallery, x.video_url, x.tags, x.services, x.client, x.project_year, x.featured, x.seo, x.rights_verified, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.projects, $jep${"id":"p3","category_id":"digital","title":"Órbita — Landing page editorial","slug":"orbita-landing","summary":"Una experiencia digital de alto contraste para presentar servicios y captar oportunidades.","body":"La estructura se diseñó alrededor de una narrativa breve, llamadas a la acción visibles y un sistema modular fácil de escalar.","blocks":[],"cover_url":"/assets/ui-portfolio.jpg","gallery":["/assets/interfaz-ui-1.jpg","/assets/interfaz-ui-2.jpg"],"video_url":null,"tags":["landing page","ui","web"],"services":["UX/UI","Desarrollo visual"],"client":"Órbita Studio","project_year":"2026","featured":true,"seo":{},"rights_verified":false,"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":0}$jep$::jsonb) as x
on conflict (id) do update set category_id = excluded.category_id, title = excluded.title, slug = excluded.slug, summary = excluded.summary, body = excluded.body, blocks = excluded.blocks, cover_url = excluded.cover_url, gallery = excluded.gallery, video_url = excluded.video_url, tags = excluded.tags, services = excluded.services, client = excluded.client, project_year = excluded.project_year, featured = excluded.featured, seo = excluded.seo, rights_verified = excluded.rights_verified, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.projects (id, category_id, title, slug, summary, body, blocks, cover_url, gallery, video_url, tags, services, client, project_year, featured, seo, rights_verified, status, published, publish_at, content_verified, sort_order)
select x.id, x.category_id, x.title, x.slug, x.summary, x.body, x.blocks, x.cover_url, x.gallery, x.video_url, x.tags, x.services, x.client, x.project_year, x.featured, x.seo, x.rights_verified, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.projects, $jep${"id":"p4","category_id":"editorial","title":"Pulso — Campaña que se siente","slug":"pulso-campana","summary":"Dirección de arte y piezas publicitarias conectadas por una idea central.","body":"Construimos una campaña adaptable a formatos digitales e impresos, con mensajes directos y una composición de gran impacto.","blocks":[],"cover_url":"/assets/diseno-fondo.jpg","gallery":["/assets/banner.jpg","/assets/diseno.jpg"],"video_url":null,"tags":["publicidad","flyers","campaña"],"services":["Concepto creativo","Publicidad"],"client":"Pulso","project_year":"2025","featured":false,"seo":{},"rights_verified":false,"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":0}$jep$::jsonb) as x
on conflict (id) do update set category_id = excluded.category_id, title = excluded.title, slug = excluded.slug, summary = excluded.summary, body = excluded.body, blocks = excluded.blocks, cover_url = excluded.cover_url, gallery = excluded.gallery, video_url = excluded.video_url, tags = excluded.tags, services = excluded.services, client = excluded.client, project_year = excluded.project_year, featured = excluded.featured, seo = excluded.seo, rights_verified = excluded.rights_verified, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.projects (id, category_id, title, slug, summary, body, blocks, cover_url, gallery, video_url, tags, services, client, project_year, featured, seo, rights_verified, status, published, publish_at, content_verified, sort_order)
select x.id, x.category_id, x.title, x.slug, x.summary, x.body, x.blocks, x.cover_url, x.gallery, x.video_url, x.tags, x.services, x.client, x.project_year, x.featured, x.seo, x.rights_verified, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.projects, $jep${"id":"p5","category_id":"illustration","title":"Milo — Personaje de marca","slug":"milo-personaje","summary":"Diseño de personaje 3D para humanizar la comunicación de una marca creativa.","body":"El personaje se desarrolló con diferentes poses, expresiones y contextos para funcionar en campañas, tutoriales y publicaciones.","blocks":[],"cover_url":"/assets/personaje-01.jpg","gallery":["/assets/personaje-03.jpg","/assets/personaje-04.jpg","/assets/personaje-06.jpg"],"video_url":null,"tags":["ilustración","personaje","3D"],"services":["Ilustración","Dirección de arte"],"client":"Proyecto personal","project_year":"2026","featured":false,"seo":{},"rights_verified":false,"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":0}$jep$::jsonb) as x
on conflict (id) do update set category_id = excluded.category_id, title = excluded.title, slug = excluded.slug, summary = excluded.summary, body = excluded.body, blocks = excluded.blocks, cover_url = excluded.cover_url, gallery = excluded.gallery, video_url = excluded.video_url, tags = excluded.tags, services = excluded.services, client = excluded.client, project_year = excluded.project_year, featured = excluded.featured, seo = excluded.seo, rights_verified = excluded.rights_verified, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.projects (id, category_id, title, slug, summary, body, blocks, cover_url, gallery, video_url, tags, services, client, project_year, featured, seo, rights_verified, status, published, publish_at, content_verified, sort_order)
select x.id, x.category_id, x.title, x.slug, x.summary, x.body, x.blocks, x.cover_url, x.gallery, x.video_url, x.tags, x.services, x.client, x.project_year, x.featured, x.seo, x.rights_verified, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.projects, $jep${"id":"p6","category_id":"branding","title":"Raíz — Identidad con origen","slug":"raiz-branding","summary":"Una marca cálida y contemporánea inspirada en materiales, territorio y oficio.","body":"El sistema visual combina una tipografía sólida, una paleta natural y composiciones editoriales para transmitir confianza y autenticidad.","blocks":[],"cover_url":"/assets/diseno.jpg","gallery":["/assets/marca.jpg","/assets/portada.jpg"],"video_url":null,"tags":["branding","logo","identidad"],"services":["Estrategia","Identidad visual"],"client":"Raíz","project_year":"2024","featured":false,"seo":{},"rights_verified":false,"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":0}$jep$::jsonb) as x
on conflict (id) do update set category_id = excluded.category_id, title = excluded.title, slug = excluded.slug, summary = excluded.summary, body = excluded.body, blocks = excluded.blocks, cover_url = excluded.cover_url, gallery = excluded.gallery, video_url = excluded.video_url, tags = excluded.tags, services = excluded.services, client = excluded.client, project_year = excluded.project_year, featured = excluded.featured, seo = excluded.seo, rights_verified = excluded.rights_verified, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.testimonials (id, name, role, company, quote, rating, rights_verified, status, published, publish_at, content_verified, sort_order)
select x.id, x.name, x.role, x.company, x.quote, x.rating, x.rights_verified, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.testimonials, $jep${"id":"t1","name":"Andrea López","role":"Fundadora","company":"Nexo","quote":"Jonathan convirtió una idea dispersa en una identidad que se siente exactamente como nosotros. El proceso fue claro, creativo y muy profesional.","rating":5,"rights_verified":false,"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":1}$jep$::jsonb) as x
on conflict (id) do update set name = excluded.name, role = excluded.role, company = excluded.company, quote = excluded.quote, rating = excluded.rating, rights_verified = excluded.rights_verified, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.testimonials (id, name, role, company, quote, rating, rights_verified, status, published, publish_at, content_verified, sort_order)
select x.id, x.name, x.role, x.company, x.quote, x.rating, x.rights_verified, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.testimonials, $jep${"id":"t2","name":"Carlos Mena","role":"Director comercial","company":"Órbita Studio","quote":"La nueva presentación de nuestra marca elevó la percepción del servicio desde el primer contacto. Recibimos un sistema, no solo piezas bonitas.","rating":5,"rights_verified":false,"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":2}$jep$::jsonb) as x
on conflict (id) do update set name = excluded.name, role = excluded.role, company = excluded.company, quote = excluded.quote, rating = excluded.rating, rights_verified = excluded.rights_verified, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.testimonials (id, name, role, company, quote, rating, rights_verified, status, published, publish_at, content_verified, sort_order)
select x.id, x.name, x.role, x.company, x.quote, x.rating, x.rights_verified, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.testimonials, $jep${"id":"t3","name":"María Fernanda Ruiz","role":"Emprendedora","company":"Raíz","quote":"Me ayudó a ordenar lo que quería comunicar y lo transformó en una marca coherente, cálida y fácil de utilizar en redes y empaques.","rating":5,"rights_verified":false,"status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":3}$jep$::jsonb) as x
on conflict (id) do update set name = excluded.name, role = excluded.role, company = excluded.company, quote = excluded.quote, rating = excluded.rating, rights_verified = excluded.rights_verified, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.faqs (id, question, answer, category, status, published, publish_at, content_verified, sort_order)
select x.id, x.question, x.answer, x.category, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.faqs, $jep${"id":"f1","question":"¿Cómo inicia un proyecto?","answer":"Selecciona un servicio y completa el cuestionario. Revisaré la información y recibirás una propuesta con alcance, tiempos, entregables y forma de pago.","category":"general","status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":1}$jep$::jsonb) as x
on conflict (id) do update set question = excluded.question, answer = excluded.answer, category = excluded.category, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.faqs (id, question, answer, category, status, published, publish_at, content_verified, sort_order)
select x.id, x.question, x.answer, x.category, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.faqs, $jep${"id":"f2","question":"¿Cuántas revisiones están incluidas?","answer":"Depende del servicio o paquete elegido. La propuesta siempre especificará las rondas incluidas. Las revisiones adicionales pueden cotizarse por separado.","category":"proceso","status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":2}$jep$::jsonb) as x
on conflict (id) do update set question = excluded.question, answer = excluded.answer, category = excluded.category, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.faqs (id, question, answer, category, status, published, publish_at, content_verified, sort_order)
select x.id, x.question, x.answer, x.category, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.faqs, $jep${"id":"f3","question":"¿Necesito tener toda la información lista?","answer":"No necesariamente. El cuestionario ayuda a detectar lo que falta. Sin embargo, textos, medidas y datos definitivos evitan retrasos durante el diseño.","category":"proceso","status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":3}$jep$::jsonb) as x
on conflict (id) do update set question = excluded.question, answer = excluded.answer, category = excluded.category, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.faqs (id, question, answer, category, status, published, publish_at, content_verified, sort_order)
select x.id, x.question, x.answer, x.category, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.faqs, $jep${"id":"f4","question":"¿Entregas archivos editables?","answer":"Sí, cuando el paquete o servicio los incluye. También recibirás formatos optimizados para impresión, web y redes según el proyecto.","category":"entregables","status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":4}$jep$::jsonb) as x
on conflict (id) do update set question = excluded.question, answer = excluded.answer, category = excluded.category, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.faqs (id, question, answer, category, status, published, publish_at, content_verified, sort_order)
select x.id, x.question, x.answer, x.category, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.faqs, $jep${"id":"f5","question":"¿Trabajas con clientes fuera de Ecuador?","answer":"Sí. El proceso puede realizarse completamente en línea mediante reuniones, correo y WhatsApp.","category":"general","status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":5}$jep$::jsonb) as x
on conflict (id) do update set question = excluded.question, answer = excluded.answer, category = excluded.category, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.faqs (id, question, answer, category, status, published, publish_at, content_verified, sort_order)
select x.id, x.question, x.answer, x.category, x.status, x.published, x.publish_at, x.content_verified, x.sort_order
from jsonb_populate_record(null::public.faqs, $jep${"id":"f6","question":"¿Los precios publicados son definitivos?","answer":"Son valores de referencia o precios base. La inversión final depende del alcance, cantidad de piezas, tiempos y complejidad.","category":"precios","status":"published","published":true,"publish_at":null,"content_verified":false,"sort_order":6}$jep$::jsonb) as x
on conflict (id) do update set question = excluded.question, answer = excluded.answer, category = excluded.category, status = excluded.status, published = excluded.published, publish_at = excluded.publish_at, content_verified = excluded.content_verified, sort_order = excluded.sort_order;

insert into public.media (id, name, storage_path, public_url, mime_type, alt_text, rights_owner, rights_verified, variants)
select x.id, x.name, x.storage_path, x.public_url, x.mime_type, x.alt_text, x.rights_owner, x.rights_verified, x.variants
from jsonb_populate_record(null::public.media, $jep${"id":"m1","name":"Portada JEP","storage_path":"legacy/m1","public_url":"/assets/portada.jpg","mime_type":"image/webp","alt_text":"Portada creativa de JEP Designer","rights_owner":"Propio","rights_verified":true,"variants":[]}$jep$::jsonb) as x
on conflict (id) do update set name = excluded.name, storage_path = excluded.storage_path, public_url = excluded.public_url, mime_type = excluded.mime_type, alt_text = excluded.alt_text, rights_owner = excluded.rights_owner, rights_verified = excluded.rights_verified, variants = excluded.variants;

insert into public.media (id, name, storage_path, public_url, mime_type, alt_text, rights_owner, rights_verified, variants)
select x.id, x.name, x.storage_path, x.public_url, x.mime_type, x.alt_text, x.rights_owner, x.rights_verified, x.variants
from jsonb_populate_record(null::public.media, $jep${"id":"m2","name":"Sistema de marca","storage_path":"legacy/m2","public_url":"/assets/marca.jpg","mime_type":"image/webp","alt_text":"Sistema visual de JEP Designer","rights_owner":"Propio","rights_verified":true,"variants":[]}$jep$::jsonb) as x
on conflict (id) do update set name = excluded.name, storage_path = excluded.storage_path, public_url = excluded.public_url, mime_type = excluded.mime_type, alt_text = excluded.alt_text, rights_owner = excluded.rights_owner, rights_verified = excluded.rights_verified, variants = excluded.variants;

insert into public.site_settings (key, value)
values ('site', $jep${"siteName":"JEP Designer","owner":"Jonathan Peña","tagline":"De la imaginación a la creatividad","email":"jepdesigner.ec@gmail.com","whatsapp":"+593 96 797 1841","whatsappRaw":"593967971841","instagram":"https://www.instagram.com/jepdesigner.ec","theme":"dark","domain":"","defaultOgImage":"/assets/portada.jpg"}$jep$::jsonb)
on conflict (key) do update set value = excluded.value;

